### ISSUE TITLE
Provide access to single precision GRIB values, latitudes and longitudes

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-data#140]
Version 2.30.0 of ecCodes and version 1.6.0 of its Python binding (this latter is yet to be released) support data values array decoded as "floats" (single-precision) to reduce memory consumption. The C function looks like this:

```C
int codes_get_float_array(const codes_handle* h, const char* key, float* vals, size_t* length);
```

The properties/methods to consider on a GRIBField are as follows:

```python
m.values
m.to_numpy()
m.to_numpy(dtype=np.float32)
m.data()
m.to_latlon()
m.to_points()
```

At the moment all these methods return double precision values. The only exception is `to_numpy(dtype=np.float32)`, but it still gets double precision values from ecCodes and performs the cast on it.

The simplest solution is to add the `dtype` option to all the methods and ensure when it is set to `np.float32` they call `codes_get_float_array` and do not perform a cast on the result.

Of course, this would not work for the `values` property.

**Comment by shahramn** [comment]
We are aiming to release the ecCodes Python bindings v1.6.0 in July 2023

**Comment by sandorkertesz** [comment]
Maybe all these methods should return `np.float32` and when users want double precision they use `dtype=np.float64`.

**Comment by sandorkertesz** [comment]
@shahramn , does `codes_get_float_array` only work for the "values" key?

**Comment by sandorkertesz** [comment]
The following methods on a `Field` and `FieldList` can now all be used with the `dtype` kwarg:

```python
 to_numpy()
data()
to_laton()
to_points()
```

When `dtype=np.float32` for GRIB data the values are fetched from eccodes with single-precison (when supported), so not cast is needed.
