### ISSUE TITLE
xarray support matching netcdf support

### ISSUE THREAD

**Issue by JamesVarndell** [ecmwf/earthkit-data#158]
### Is your feature request related to a problem? Please describe.

xarray wrapper objects should have all of the same features as netcdf reader objects - i.e. support `ls`, `metadata` etc.

**Comment by sandorkertesz** [comment]
@JamesVarndell, do you think we need a `to_fieldlist` method on `XArrayDatasetWrapper` to expose the xarray object as a FieldList?
