### ISSUE TITLE
Earthkit FDB Unknown reader

### ISSUE THREAD

**Issue by victoria-cherkas** [ecmwf/earthkit-data#174]
### What happened?

Hi there,

I have set up an FDB instance and I am trying to run your tutorial to read from our FDB with earthkit.data as in the notebook https://github.com/ecmwf/earthkit-data/blob/develop/docs/examples/fdb.ipynb

However the reader is defined as Unknown, and so on trying to loop through the GribFields, i get the error `AttributeError: 'Unknown' object has no attribute '__next__'`

```
ds = earthkit.data.from_source("fdb", request)
for f in ds:
    print(f)
```

Why is the reader defined as Unknown instead of grib?

Thanks a lot.

### What are the steps to reproduce the bug?

The only difference from your notebook is the schema, and that I set `os.environ['FDB_HOME']` and `os.environ['FDB5_CONFIG']` before the `earthkit.data.from_source("fdb", request)`. I can read from FDB with pyFDB, with these same variables.

### Version

earthkit-data  0.3.0,  pyfdb 0.0.3 

### Platform (OS and architecture)

x86_64 GNU/Linux

### Relevant log output

```shell
Exception has occurred: AttributeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
'Unknown' object has no attribute '__next__'
  File "/scratch/e1000/meteoswiss/scratch/vcherkas/miniconda3/envs/fdb/lib/python3.7/site-packages/earthkit/data/sources/stream.py", line 83, in __next__
    return self._reader.__next__()
  File "/scratch/e1000/meteoswiss/scratch/vcherkas/fdb-python-sandbox/demo.py", line 31, in <module>
    for f in ds:
  File "/scratch/e1000/meteoswiss/scratch/vcherkas/miniconda3/envs/fdb/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/e1000/meteoswiss/scratch/vcherkas/miniconda3/envs/fdb/lib/python3.7/runpy.py", line 193, in _run_module_as_main (Current frame)
    "__main__", mod_spec)
AttributeError: 'Unknown' object has no attribute '__next__'
```

### Organisation

MeteoSwiss

**Comment by sandorkertesz** [comment]
Dear @victoria-cherkas, thank you for reporting this issue. A hotfix release will be available soon.

**Comment by victoria-cherkas** [comment]
Dear @sandorkertesz thanks a lot for the quick response and release! 
With the hotfix the reader is now <earthkit.data.readers.grib.memory.GribStreamReader>

Unfortunately I can't say whether this works to actually read my data, but that is probably a pyFDB issue. (I can list records but not retrieve with pyFDB)

**Comment by sandorkertesz** [comment]
Dear @victoria-cherkas, I just would like to ask you if this issue was sorted out or there is still some work required on the earthkit-data side.

**Comment by victoria-cherkas** [comment]
Dear @sandorkertesz Sorry I should have updated this issue - yes I can now read FDB from earthkit data, no further work needed, thanks! The issue was with our MARS definitions, and we had help to resolve these now.

**Comment by sandorkertesz** [comment]
Thanks, I will then close this issue.
