### ISSUE TITLE
NetCDF reader not initiated correctly

### ISSUE THREAD

**Issue by EddyCMWF** [ecmwf/earthkit-data#187]
### What happened?

ek-data is failing to initialise properly for some netCDF files. Uncertain what the conditions are to get to this code, but here is an example CDS request that causes it:
```
ek_ch4_cds = ek.data.from_source(
    "cds",
    "satellite-methane",
    {
        'processing_level': 'level_2',
        'sensor_and_algorithm': 'tanso2_fts2_srfp',
        'year': '2021',
        'month': '01',
        'day': '01',
        'version': '2.0.0',
        # 'format': 'zip',
    }
)
ek_ch4_cds
```

### What are the steps to reproduce the bug?

Initialise NetCDFReader with path, not with self

### Version

latest

### Platform (OS and architecture)

MacOS + Linux

**Comment by sandorkertesz** [comment]
Hi @EddyCMWF, please can you provide some more details?
