### ISSUE TITLE
Long test failure

### ISSUE THREAD

**Issue by malmans2** [ecmwf/earthkit-data#233]
### What happened?

I get a failure when I run long tests, and I noticed that none of the tests affected by the PRs I've submitted run on GitHub.

If that's not done on purpose, it looks like the unit-tests and integration-tests actions do the same thing, perhaps the integration tests could use the `-E long` flag.

### What are the steps to reproduce the bug?

```
git clone git@github.com:ecmwf/earthkit-data.git
mamba env create -n earthkit-data -f tests/environment-unit-tests.yml
conda activate earthkit-data
pip install -e .
python -m pytest -vv -m 'not notebook and not no_cache_init' --cov=. --cov-report=$(COV_REPORT) -E long
```

### Version

0.4.1.dev27+g7a11635

### Platform (OS and architecture)

Darwin MacBook-Pro-3.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

### Relevant log output

```shell
FAILED tests/sources/test_cds.py::test_cds_non_observation_csv_file_to_pandas_xarray - Exception: the request you have submitted is not valid. There is no data matching your request. Check that you have specified the correct fields and values..
```

### Organisation

B-Open / CADS-EQC

**Comment by sandorkertesz** [comment]
This test is now disabled in the develop branch.

**Comment by EddyCMWF** [comment]
hmm, this is because the data provider has broken the dataset on the CDS. I'll change it to a static dataset, i.e. one without automatic upates which could potentially break in the future, and report the dataset issue to Eduardo

**Comment by malmans2** [comment]
Got it, thanks.
I have a related question: How does the cache deal with dynamic datasets?

**Comment by EddyCMWF** [comment]
> Got it, thanks. I have a related question: How does the cache deal with dynamic datasets?

Good question, I suspect it doesn't, I'll get back to you on this.
Did cads-toolbox+cachelote have anything in place to handle this? I don't see a way of implementing it without additional knowledge of the source you are accessing. TBH, this is a new (undoubtly long) ticket!

**Comment by malmans2** [comment]
Nothing has been implemented for cads-toolbox, but the cache accepts settings such as tags and expirations that are used to clean/invalidate specific cache entries. It does require knowledge of the source if dynamic datatasets do not have public tags/metadata, but it should allow to deal with those datasets.
