### ISSUE TITLE
Cache cleaner policy

### ISSUE THREAD

**Issue by malmans2** [ecmwf/earthkit-data#245]
Hi there,
I have a quick question. Which policy does the cache cleaner use?
LRU, LFU, or something else?
Thanks.

**Comment by sandorkertesz** [comment]
These are the queries used for the cleaning:

```
"SELECT * FROM cache WHERE size IS NOT NULL AND owner='orphans' AND creation_date < ?",
"SELECT * FROM cache WHERE size IS NOT NULL AND creation_date < ? ORDER BY last_access ASC",
```
So it removes the "orphan" entries and then the least recently accessed ones until the total size goes below the limit.

**Comment by malmans2** [comment]
Thanks!
