### ISSUE TITLE
Make some dependencies optional

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-data#252]
### What maintenance does this project need?

Requirements file needs to be revised for earthkit-data as it installs too many things. We could solve that through optional dependencies in the `toml` config, for instance having an option to install all dependencies, or just a subset, or just the basic ones.

### Organisation

ECMWF

**Comment by sandorkertesz** [comment]
At the moment, there are these sources requiring additional packages/libraries:

- "cds", "ads": cdsapi
- "mars": ecmwf-api-client
- "ecmwf-opendata": ecmwf-opendata
- "polytope": polytope-client
- "wekeo", "wekeo-cds": hda
- "fdb": pyfdb

We have two options to make any of them optional:
1. turn the source into a plugin. E.g. "polytope" source can be implemented as the"earthkit-data-polytope" plugin. So it will only be available when the user installs it (and this will install all its dependencies)
2. make the dependency optional in the config and print a proper error message when someone wants to use a source where the dependency is not installed.

**Comment by sandorkertesz** [comment]
There is also the question of the supported data file formats. The following list contains the current formats and their (Python) dependencies:

"grib": eccodes, (cfgrib, xarray for `to_array`)
"bufr": pdbufr
"odb": pyodc, (pandas for `to_pandas`)
"netcdf": netcdf4, xarray
"csv": (pandas for `to_pandas`)

Please note that when xarray is used currently dask is required too.

**Comment by tlmquintino** [comment]
If we start by just making the dependency optional, I think it will be simpler/quicker.
Then later we can consider plugins, and separate repos etc.
