### ISSUE TITLE
Support for array modules other than Numpy

### ISSUE THREAD

**Issue by jinmannwong** [ecmwf/earthkit-data#257]
### Is your feature request related to a problem? Please describe.

It would be useful if earthkit.data.NumpyFieldList did not explicitly depend on numpy so that it could be used for other array modules. Or, since numpy is in the name, maybe have a more generic array field list that is agnostic of the underlying array type. This would be useful for supporting array modules such as Cupy or JAX for GPUs. 

### Describe the solution you'd like

Modification of the existing NumpyFieldList or a new field list class which does not depend on a specific array module. One could go about this by, for example, using https://pypi.org/project/array-api-compat.

### Organisation

ECMWF

**Comment by sandorkertesz** [comment]
Array `backends` are implemented in the `feature/array` branch. At the moment it, allows using "numpy" (this is the default) and "pytorch" backends via `arrray_compat_api`. The following example: 

https://earthkit-data.readthedocs.io/en/feature-array/examples/grib_array_backends.html

shows how it works with a `pytorch` backend.

TODO:
- add tests
- add documentation
- add cupy
- implement saving to grib files
- review the usage of `FieldList.to_fieldlist()`
