### ISSUE TITLE
Use ECMWF's downstream-ci in GitHub Actions

### ISSUE THREAD

**Issue by iainrussell** [ecmwf/earthkit-data#259]
### What maintenance does this project need?

To make earthkit-data's ci work in the same way as other ECMWF packages, the following should be done:

- add to downstream-ci as per instructions [here](https://confluence.ecmwf.int/display/DS/Checklist%3A+How+to+add+a+package+to+downstream+CI)
- dependencies in the tree for now should be eccodes-python, cfgrib and pdbufr; very likely pyfdb and pyodc should be there too; for now, earthkit-meteo can be taken from PyPi
- any ci actions that are special to this package (e.g. the no-eccodes environment) should be in a separate yml file
- revise the cd action as per instructions [here](https://confluence.ecmwf.int/display/DS/GitHub+Actions+PyPI+CD)

Thank you!

### Organisation

ECMWF

**Comment by sandorkertesz** [comment]
Fixed by #262
