### ISSUE TITLE
Create readthedocs page for documentation

### ISSUE THREAD

**Issue by corentincarton** [ecmwf/earthkit-data#36]
@sandorkertesz or @JamesVarndell, I see there's a docs folder. Would it be possible to put the documentation on readthedocs or is it too soon?

**Comment by sandorkertesz** [comment]
Hi @corentincarton , at the moment, there is no proper documentation available, so it has to be written first, then it can be hosted on read the docs.

**Comment by corentincarton** [comment]
We already have a bunch of notebooks, right? We could use that as a start. I think it would be nice so that people don't need to clone the code, build an environment and run the notebooks to see how earth-kit data works.

**Comment by corentincarton** [comment]
Ah you're right, I forgot it was well displayed on GitHub.

**Comment by corentincarton** [comment]
This is great @sandorkertesz ! One last thing, it would be good to add the link in the readme!

**Comment by sandorkertesz** [comment]
I already added it but it is in a branch and yet to be merged into main!
