### ISSUE TITLE
Error when reading mars request with only one date

### ISSUE THREAD

**Issue by corentincarton** [ecmwf/earthkit-data#421]
### What happened?

I get the following error
`AttributeError: 'str' object has no attribute 'to_datetime_list'`
when providing only one date as a string to the mars request.

### What are the steps to reproduce the bug?

You can reproduce the issue with the following request:
```fc_request = {
    "class": "ce",
    "date": "2024-06-12",
    "expver": 1,
    "levtype": "sfc",
    "model": "lisflood",
    "origin": "ecmf",
    "param": "240023",
    "step": "6/to/240/by/6",
    "stream": "efas",
    "time": "00:00:00",
    "type": "pf",
    "number": "1/to/50",
}
fc = earthkit.data.from_source("mars", fc_request)
```

### Version

feature/earthkit-engine

### Platform (OS and architecture)

HPC

**Comment by sandorkertesz** [comment]
@corentincarton, thank you for reporting this issue. It was only a problem in the `feature/earthkit-engine` branch where  it is fixed now. So I close this issue.
