### ISSUE TITLE
Use python for sample file downloads in notebooks

### ISSUE THREAD

**Issue by samsammurphy** [ecmwf/earthkit-data#52]
The notebooks currently use bash to download sample files if not already on disk

![Screenshot 2023-05-04 at 16 02 51](https://user-images.githubusercontent.com/16657983/236248381-d5ffdd9e-171d-4206-85bb-12888f3fd081.png)

I really like this ^ one liner, however, users might not have `wget` installed on their machine necessarily. I say this because I was surprised to learn that I did not installed wget on my macbook yet (even if it is on every other machine I use).

Anywhos.. users will have python installed (presumably) if they are running this notebook, from the user's perspective downloading sample data might look something like 

![Screenshot 2023-05-04 at 16 06 58](https://user-images.githubusercontent.com/16657983/236249468-c5d5731f-a161-40c7-9e48-749e801488d0.png)

which is a bit easier to read. 

Here is an example python function (which I guess in practice will be a class method somewhere)...

```
import os
import urllib.request

def download_sample_file(filename):
    
    base_url = "https://get.ecmwf.int/repository/test-data/emohawk/examples/"
    data_url = base_url + filename
    
    if not os.path.isfile(filename):
        urllib.request.urlretrieve(data_url, filename)
```

**Comment by sandorkertesz** [comment]
Good idea. The path builder methods are already defined in testing.py.

**Comment by samsammurphy** [comment]
PR merged into dev https://github.com/ecmwf/earthkit-data/pull/106
