### ISSUE TITLE
Enable controlling settings via environment variables

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-data#561]
### Is your feature request related to a problem? Please describe.

Currently, the settings can only be controlled via the `~/.earthkit-data/settings.yaml` file or from Python using the `earthkit.data.settings` interface. Additionally, it would be useful (e.g. in ecflow)  if we were able to control the settings via env variables too.

It is not clear whether we should add an env variable for each settings or only for a subset of these. The proposal here is to  only add env variables for the settings controlling the cache and the temporary directory:

- cache-policy
- temporary-cache-directory-root
- temporary-directory-root
- maximum-cache-size
- maximum-cache-disk-usage

The env variables should be all upper-case prefixed with EARTHKIT_DATA. E.g.:

cache-policy -> EARTHKIT_DATA_CACHE_POLICY

### Organisation

ECMWF

**Comment by sandorkertesz** [comment]
Some more details to discuss.

Assume the EARTHKIT_DATA_CACHE_POLICY env variable is defined. The question is what should happen in the following calls.

```python
from earthkit.data import settings
```

get
-----
```python
settings.get("cache-policy")
```
This should return the value of  EARTHKIT_DATA_CACHE_POLICY.

reset
-------
```python
settings.reset()
settings.get("cache-policy")
```
`reset()` resets the settings to the defaults and updates the settings file. What should `get()` return in this case?  Still EARTHKIT_DATA_CACHE_POLICY?

set
------
```python
settings.set("cache-policy", "off")
settings.get("cache-policy")
```
`set()` changes the settings and updates the settings file. What should get return after calling it? Still EARTHKIT_DATA_CACHE_POLICY?

context manager
------------------
```python
with settings.temporary():
    settings.set("cache-policy", "off")
    settings.get("cache-policy")
```
Not clear what to do in this case.

**Comment by iainrussell** [comment]
Perhaps we need to make it explicit - something like:
```
settings.set("settings-policy", "override-with-env-vars")
```
and from that moment on, all getting of settings will use the corresponding env var if it exists (and setting will do nothing), otherwise, if the env var does not exist, behaviour is as before. (If having a setting to control the settings is a bit too 'meta', we can make it an explicit function: `settings.set_policy("override-with-env-vars")`)

As for which settings we can control like this, why not make it generic - we can figure out the env var name from the setting name (lower->upper case, and hyphens->underscores).

**Comment by sandorkertesz** [comment]
@iainrussell, thank you for the suggestion. Unfortunately, with this it would be much harder to control earthkit.data since we would not know in advance what would be the effect of setting an environment variable.
