### ISSUE TITLE
Use empty string for missing standard_name attribute in coordinate array(s) of a netcdf

### ISSUE THREAD

**Issue by samsammurphy** [ecmwf/earthkit-data#62]
[NetCDFReader](https://github.com/ecmwf/earthkit-data/blob/68d755906d8ce15c214345e07539b7a4e9af4b0f/earthkit/data/readers/netcdf.py#L234) does not work if `standard_name` attribute is missing from coordinate data array

This is because we would be trying to use the string method lower() on a None type

Here are a couple of ideas for fixes

1. use an empty string for missing `standard_name` (as opposed to None)
2. alternatively.. test for None before calling .lower()

I recommend the first option. It would be something like replacing [this line](https://github.com/ecmwf/earthkit-data/blob/68d755906d8ce15c214345e07539b7a4e9af4b0f/earthkit/data/readers/netcdf.py#LL300C28-L300C28) with..

```
# this will assign an empty string to standard_name if c (coordinate data array) has no attribute called standard_name
standard_name = getattr(c, "standard_name", '')
```

The second option might look something like replacing [this line](https://github.com/ecmwf/earthkit-data/blob/68d755906d8ce15c214345e07539b7a4e9af4b0f/earthkit/data/readers/netcdf.py#L307) with..

```
# if standard_name is None then will not run standard_name.lower()
standard_name and standard_name.lower() in GEOGRAPHIC_COORDS["x"]

```
Let me know preferred approach (if either or other) and I can open a PR

**Comment by samsammurphy** [comment]
I opened this PR https://github.com/ecmwf/earthkit-data/pull/65 to resolve this issue

**Comment by sandorkertesz** [comment]
PR #65 has been merged, I suggest you close this issue.
