### ISSUE TITLE
Should we be using a dev branch?

### ISSUE THREAD

**Issue by samsammurphy** [ecmwf/earthkit-data#66]
### Is your feature request related to a problem? Please describe.

Merging feature branches directly into `main` slows down development time and perhaps creates too many releases.

### Describe the solution you'd like

Short answer = Branch features from dev and only merge dev into main on a release.

Longer answer

`main`: The main branch stores the official release history. All commits in the main branch represent a version of the project that is deployable and has been thoroughly tested.

`dev`: The dev branch is where the next release will be developed. The dev branch is a copy of the main branch where all the features approved for the next release are integrated.

`feature`: A feature branch is created from dev for developing new features for the upcoming or a distant future release. When a feature is complete, it is merged into the dev branch.

### Organisation

ECMWF

**Comment by tlmquintino** [comment]
these are not the official names used at ECMWF:
- main
- develop
- feature/<description>

**Comment by tlmquintino** [comment]
the reason earthkit data is/was develop without branches is because it was still in infancy and changing too much and there was no software lifecycle management needed.
Now that many developers are contributing and it starts to be more stable, it is probably time to introduce branches.

**Comment by sandorkertesz** [comment]
The develop branch has been added.
