### ISSUE TITLE
Fix pip install for earthkit-data

### ISSUE THREAD

**Issue by samsammurphy** [ecmwf/earthkit-data#70]
### What happened?

The installation guide for earthkit-data in [the docs](https://earthkit-data.readthedocs.io/en/latest/install.html) does not seem to work currently

### What are the steps to reproduce the bug?

What I tried
```
$ pip install earthkit-data
$ python

import earthkit.data
```
results in a `ModuleNotFoundError: No module named 'earthkit`

So I also tried

```
$ pip install earthkit
```

but this did not fix the issue

### Version

earthkit_data-0.1.0

### Platform (OS and architecture)

Darwin Samuels-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

**Comment by samsammurphy** [comment]
p.s. for now / development of the [app I am building](https://github.com/ecmwf-projects/hat) I installed earthkit-data in edit mode in that app's python environment 

```
$ conda activate external_app_env
$ cd /path/to/earthkit-data/source-code
$ pip install -e .
```

**Comment by sandorkertesz** [comment]
Version 0.1.2 is now on pypi and works.
