### ISSUE TITLE
Implement caching control

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-data#89]
The current caching mechanism (taken from climetlab) behaves as follows:

- the cache directory is always kept between sessions
- there are no useful public methods (e.g. cleanup) on the `earthik.data.cache` object that is exposed in the public API 
- the cache stores:
    - data retrieved e.g. from MARS
    - data downloaded from URLs
    - data extracted from an archive (e.g. tar)
    - GRIB metadata index DB
    - message offset/length information  for each grib file (in a json file)
- `from_source()` always tries to use the data from cache. E.g. only performs a MARS retrieval if the data is not found in the cache.

The task is to allow fine tuning of all the aspects of caching.

**Comment by sandorkertesz** [comment]
The simplest solution, as far as the API is concerned, would be to add a "cache-policy " option to the settings, e.g. with the following modes:

- "no-cache": no cache is used. GIRB metadata/offset index is kept in memory. "cds", 'mars", "url" etc do not work
- "persistent": cache directory is not deleted in the end
- "tmp": cache directory is deleted in the end

In an operational environment we could use it like this:

```
import earthkit.data
s = earthkit.data.settings.temporary():
s.set("cache-policy", "no-cache")
```

or 

```
import earthkit.data
s = earthkit.data.settings.temporary(name="cache-policy", "no-cache"):
```

This would create a temporary settings object (not written to disk), and no cache directory would be created/used.

**Comment by tlmquintino** [comment]
@sandorkertesz what is the meaning of temporary() here? what does it return?
Would it not be simpler to just have a settings object and do:
`s = earthkit.data.settings().set("cache-policy", "no-cache")`

Also, I think the default should probably be "no-cache", meaning we do not create files in disk if the user does not ask for it.

**Comment by tlmquintino** [comment]
Further idea:

1. Make it a Policies object
2. Name keys more specific to 'index-cache' as we may have other caches in the future
3. Name tmp to temporary -- its clearer

The above results in the usage:

`s = earthkit.data.settings.policies().set("index-cache", "temporary")`

**Comment by oiffrig** [comment]
Maybe something inspired by `matplotlib.rcParams`? https://github.com/matplotlib/matplotlib/blob/v3.7.1/lib/matplotlib/__init__.py#L629-L794

That way you can easily support external configuration (i.e. a config file), and temporary changes from within a script.
We could even add a context manager for scoped changes:
```python
with earthkit.data.policy(cache=False):
    ...
```

**Comment by sandorkertesz** [comment]
> Maybe something inspired by `matplotlib.rcParams`? https://github.com/matplotlib/matplotlib/blob/v3.7.1/lib/matplotlib/__init__.py#L629-L794
> 
> That way you can easily support external configuration (i.e. a config file), and temporary changes from within a script. We could even add a context manager for scoped changes:
> 
> ```python
> with earthkit.data.policy(cache=False):
>     ...
> ```

Thanks for the suggestion. As you can see `earthkit.data.settings` already works in a similar way.

**Comment by sandorkertesz** [comment]
> Further idea:
> 
>     1. Make it a Policies object
> 
>     2. Name keys more specific to 'index-cache' as we may have other caches in the future
> 
>     3. Name tmp to temporary -- its clearer
> 
> 
> The above results in the usage:
> 
> `earthkit.data.settings.policies().set("index-cache", "temporary")`

@tlmquintino What would be the benefit of having a separate policies object instead of just using the `settings` e.g. like this: 

```python
earthkit.data.settings.set("index-cache-policy", "temporary")
```
