### ISSUE TITLE
Provide a convenience function which returns geographic data points on the original coordinate reference system

### ISSUE THREAD

**Issue by JamesVarndell** [ecmwf/earthkit-data#91]
### Is your feature request related to a problem? Please describe.

At the moment there is an inconsistency between what the `to_points` method returns from `GribField` objects vs `NetcdfField` objects, in that the netCDF objects will return the x and y points of the data _in the data's coordinate reference system_, whereas `GribField`s always return an array of lat/lon points.

### Describe the solution you'd like

I think that `to_points` should always return the geographic x and y points of the data in the data's original CRS. We should also perhaps offer a `to_latlon` (or similar) method, which explicitly does the translation to latitudes and longitudes.

### Organisation

ECMWF

**Comment by tlmquintino** [comment]
I would say the solution is that for now, in those circumstances, we throw exception in `to_points()` and when the grid library is there, we then do the right thing.

**Comment by tlmquintino** [comment]
I to like the distinction of `to_points` and `to_latlong` as @JamesVarndell described.

**Comment by sandorkertesz** [comment]
Currently `to_points` returns a dict as `{"lat": ndarray, "lon": ndarray}` . What would be the keys in the new version?

**Comment by sandorkertesz** [comment]
I will then add `to_latlon` to return the latitudes and longitudes for GRIB fields. We still need to figure out what keys `to_points` should return for GRIBs where to original crs is known.

**Comment by sandorkertesz** [comment]
This was fixed by #102
